name: test

on:
  push:
    branches:
      - '**'

jobs:

  test:
    name: test
    runs-on: ubuntu-22.04
    steps:
      - name: 📦 Upload fuzzer corpus backup to Manticore S3
        if: always()
        run: |
          mkdir -p build/src/fuzzer/corpus
          echo 123 > build/src/fuzzer/corpus/file1
          echo 123 > build/src/fuzzer/corpus/file2
          
          cd build/src/fuzzer/
          tar -czf corpus.tar.gz corpus
          mkdir corpus-backup
          mv corpus.tar.gz corpus-backup
          cd corpus-backup
          docker run --rm -v $(pwd):/upload manticoresearch/upload fuzzy-tests-corpus
